AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Custom:
    Type: Custom::Custom
    Properties:
      Value: Hello World!
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:{{cookiecutter.project_name}}'
Outputs:
  CustomValue:
    Value: !GetAtt 'Custom.Value'
